### ISSUE TITLE
Comparing LibGit2Sharp blows with "Format of the executable (.exe) or library (.dll) is invalid."

### ISSUE THREAD

**Issue by andreasohlund** [ParticularLabs/APIComparer#47]
To repro just execute

http://localhost:2321/compare/LibGit2Sharp/0.20.1...0.20.2

causes Mono.Cecil to blow with mentioned ex.

**Comment by andreasohlund** [comment]
cc @SimonCropp @nulltoken

**Comment by nulltoken** [comment]
@andreasohlund :heart: for having taken a look at this.

>causes Mono.Cecil to blow with mentioned ex.

Most certainly due to trying to load one of the native binaries as a managed one.

A `try/catch (BadImageFormatException e)` should work around this. FWIW, this is the way it's been **[solved](https://github.com/scriptcs/scriptcs/pull/250/files#diff-495af50f3c53e3464687ee27ac2308fdR94)** by the scriptcs project

**Comment by nulltoken** [comment]
Unless someone beats me to it, I'll try to send a PR tomorrow. Cool with you?

**Comment by andreasohlund** [comment]
That would be awesome. One way to integration test this would be to add a
similar test to

**Comment by andreasohlund** [comment]
We have some code in NServiceBus to exclude non .net asm that could be used as inspiration :)

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs#L171
