### ISSUE TITLE
Url conventions

### ISSUE THREAD

**Issue by andreasohlund** [ParticularLabs/APIComparer#8]
The plan is to build and release a basic comparison page based on a url convention

### Url rules
* `/Compare/NServiceBus/4.7.7...5.2.0`
* `/Compare/NServiceBus/4.7...5.2` - Compare max(4.7) vs max (5.2) from a semver perspective.
* `/Compare/NServiceBus/4...5` - Compare max(4) vs max (5) from a semver perspective
* `/Compare/NServiceBus/`   -  compare the 2 latest stable versions from nuget.org

Note: the urls with non deterministic version will do a temp redirect based on the the current version history we have at the moment

### Request for unprocessed nuget

* Setup signalr channel
* Return a page with a spinner
* Queue up a `ProcessNuGetRequest`: Name, LeftVersion, RightVersion
* When done processor publishes `NewComparisonAvailable` / NuGetNotFound / VersionNotFound
* Push those over signalr to notify user

### Plan of attack

- [x] Setup a Azure website: particular-apicomparer-live
- [x] Setup a cname for apicomparer.particular.net
- [x] Setup a web job for the "NuGetProcessor"

### Out of scope for now

* Allow users to register an email if it takes long
* To return json for programmatic comparisons
* Comparing packages that have been splitted

**Comment by andreasohlund** [comment]
@ParticularLabs/apicomparer please comment

**Comment by SeanFeldman** [comment]
A few suggestions

1. To use GTM instead of GA. GTM is already used for [particular.net](http://particular.net) site [here](https://www.google.com/tagmanager/web/#management/Containers/a30559134c0/)
2. Results can be shared between instances of azure web site by simply keeping files within web root. Webjobs have full access to those files as well.

**Comment by danielmarbach** [comment]
I'm currently setting up the website and webjob

**Comment by danielmarbach** [comment]
Was a bit trickier than I fought to get the proposed URI format working. Now it is running. What about the following URI format?

`compare/NServiceBus/4.7/to/5.2`

would be better readable I think

**Comment by danielmarbach** [comment]
@SimonCropp  I see that you have been using Nancy and Handlebars in the docs web. Should I remove the website branch and restart with that technology stack?

**Comment by danielmarbach** [comment]
A few more ideas:
- Put files onto CDN
- Controller checks according to convention for file existence and renders that. Only if not present it sends the command. Otherwise the file will be streamed of the CDN.

**Comment by SimonCropp** [comment]
The problem with compare/NServiceBus/4.7/to/5.2. Is that it kind of implies compare/NServiceBus/4.7/to/ is also a resource.

**Comment by SimonCropp** [comment]
As for nancy vs mvc. I have worked on a few project using each and i have always found nancy to have less friction, easier to extend and generaly fewer yaks.

That is unless someone is 100% sold on moving to mvc vnext... .

**Comment by SimonCropp** [comment]
As for view engine. When i built the docs site i wanted the most github compatible markdown rendering engine. I considered engines written in various languages. The result, at that time, was marked js. So to get that to work i had to solve the problem of communication between .net and js. With that problem  solved, when considering rendering engines, i also looked through js engines. Hence settling on handlebars.

With the apicomparer site we dont have the requirment of github md compat. So instead of marked js i would consider commonmark via https://github.com/Knagis/CommonMark.NET

And the view engine... Anything that can easily be be used to generate html files outside the context of a website. Last time i looked at razor it was not friendly to be used outside the web context.

**Comment by SimonCropp** [comment]
As for cdn. There will only be siginficant improvements with a cdn if we can avoid the double hop of the website hacing to check for existence before returning the url

**Comment by andreasohlund** [comment]
I'm +1 for Nancy, unless we see value in switching to asp.net 5? (is that
to early?)

**Comment by danielmarbach** [comment]
@andreasohlund I’ll change that. Now I got a better understanding where we are heading too. So I’ll close this branch and restart with nancy

**Comment by danielmarbach** [comment]
@andreasohlund and @SimonCropp I talked to @SeanFeldman today and he helped me out to get the website running. He would be very motivated to help out. We need to make sure to include him as well!

**Comment by SeanFeldman** [comment]
Connected with @brittking to get GTM going

**Comment by andreasohlund** [comment]
There is a @ParticularLabs/apicomparer team that contains interested people so please ping that team to make sure all relevant people can chime in
